- src: http://github.com/websoft9/role_common
- src: http://github.com/websoft9/role_jdk
- src: https://github.com/Websoft9/role_elasticsearch
- src: https://github.com/hnczhjh/role_kibana
- src: https://github.com/hnczhjh/role_logstash
- src: http://github.com/websoft9/role_preend
- src: http://github.com/websoft9/role_end